# Generated by Django 3.2 on 2023-11-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaints',
            new_name='complaint',
        ),
    ]
