# Generated by Django 3.2 on 2023-11-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_complaints_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaintdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='name',
            new_name='incidenttype',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='phno',
            new_name='yourcontactinformation',
        ),
    ]
