# Generated by Django 3.2 on 2023-11-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231121_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='crimereport',
        ),
    ]
