# Generated by Django 3.2 on 2023-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_complaint_crimereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='incidenttype',
            field=models.CharField(max_length=50),
        ),
    ]
